### ISSUE TITLE
Code to generate prompts from Time Series

### ISSUE THREAD

**Issue by natalialmg** [HaoUNSW/PISA#1]
Hi, I would like to do a similar work to the one presented in PISA but with a custom dataset. I tried to find the code to generate the prompts from the time series data but I did not find it in this repository. Is it available here? If not, are you planning to make it available any time soon? Thank you!

**Comment by HaoUNSW** [comment]
Hi @natalialmg 

Sorry for the delay. Basically, we used the prompt template (as given in the paper) to the prompting. For a custom dataset, a tailored template might be needed. We have uploaded the prompting script for the three sub-sets used in PISA. You can probably do something similar for your custom dataset.

**Comment by Oytpzy** [comment]
Hello, I am a student and would like to learn about your code process. Therefore, I would like to use your published validation set to debug the code, but when running run_hf.py, it shows that it cannot be accessed https://huggingface.co/google_pegasus-xsum/resolve/main/config.json. May I ask how could I do？

**Comment by Zero-coder** [comment]
> 您好，我是一名学生，想了解您的代码过程。因此，我想使用您发布的验证集来调试代码，但是在运行run_hf.py时，它显示无法 https://huggingface.co/google_pegasus-xsum/resolve/main/config.json 访问它。请问我该怎么办？

hey there, try vpn, v2ray or clash,

**Comment by suchenjm** [comment]
请问这个问题解决了吗，怎么解决的呀，求求了

**Comment by suchenjm** [comment]
> > 您好，我是一名学生，想了解您的代码过程。因此，我想使用您发布的验证集来调试代码，但是在运行run_hf.py时，它显示无法 https://huggingface.co/google_pegasus-xsum/resolve/main/config.json 访问它。请问我该怎么办？
> 
> hey there, try vpn, v2ray or clash,

/

**Comment by suchenjm** [comment]
我已经使用clash，并进已经login in，应该如何解决他：
OSError: google_pegasus-xsum is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
