### ISSUE TITLE
Hello! Asking for other data prompts

### ISSUE THREAD

**Issue by Zero-coder** [HaoUNSW/PISA#4]
Thanks for your splendid work, but I have only discovered val_x_prompt and val_y_promt in "PISA-Prompt", could you please provide  train and test prompt.txt ~, thanks for providing such insight in your paper, nice work, I enjoy watching the limitation and future work discussion, it's very interesting and perspective.
Dataset

|── PISA-Prompt
    │── CT
        │-- train_x_prompt.txt
        │-- train_y_prompt.txt
        │-- val_x_prompt.txt
        │-- val_y_prompt.txt
        │-- test_x_prompt.txt
        │-- test_y_prompt.txt
    │── ECL
        │-- train_x_prompt.txt
        │-- train_y_prompt.txt
        │-- val_x_prompt.txt
        │-- val_y_prompt.txt
        │-- test_x_prompt.txt
        │-- test_y_prompt.txt  
    │── SG
        │-- train_x_prompt.txt
        │-- train_y_prompt.txt
        │-- val_x_prompt.txt
        │-- val_y_prompt.txt
        │-- test_x_prompt.txt
        │-- test_y_prompt.txt

**Comment by peisong-zhang** [comment]
the author has already shared it in google cloud

**Comment by xuehaouwa** [comment]
Hi @Zero-coder 

Please check the shared google cloud folder. Let me know if you find something I missed. Thx!

**Comment by Zero-coder** [comment]
Thanks，I really appreciate your working and respondance. Have a good day~🙂

**Comment by suchenjm** [comment]
Hi，Where should I find the google cloud link，
