### ISSUE TITLE
Question about case study

### ISSUE THREAD

**Issue by DorisFangWork** [HaoUNSW/PISA#5]
I tried the case study, copied the prompt to ChatGPT, below is the output, I would like to double confirm, is this the same as how you get the output? It's just average of all numbers.
![image](https://github.com/HaoUNSW/PISA/assets/72718674/a292e4bb-a60a-4a7f-848d-db63de65dc08)

**Comment by xuehaouwa** [comment]
Yes, that's also what we found during our experiments. In most of the cases where ChatGPT can yield predicted numbers, it would be the average. We also report this in our paper.
