### ISSUE TITLE
源码运行遇到一些问题

### ISSUE THREAD

**Issue by suchenjm** [HaoUNSW/PISA#7]
$ python cmd_inference.py
Traceback (most recent call last):
File "cmd_inference.py", line 7, in
from calculate_bleu import metric_with_missing_rate
ModuleNotFoundError: No module named 'calculate_bleu'

请问calculate_bleu是哪个包

**Comment by HaoUNSW** [comment]
Hi, I have updated the code to resolve this. It's actually the metrics.py
